"""Universal helper functions"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['move_columns', 'clean_string', 'clean_col_names', 'show_identical_columns', 'reduce_mem_usage', 'group_resample',
           'polars_resample']

# %% ../nbs/00_core.ipynb #f2023e00
import pandas as pd
import polars as pl
import itertools

# %% ../nbs/00_core.ipynb #858a00a6
def move_columns(
    df: pd.DataFrame,  # Input
    cols_to_move: str,  # Single 
    pos: int  # Target
) -> pd.DataFrame:
    """
    Move one or more columns to a specified position in a DataFrame.
    """

    if isinstance(cols_to_move, str):
        cols_to_move = [cols_to_move]

    cols = list(df.columns)

    for c in cols_to_move:
        cols.remove(c)

    new_cols = cols[:pos] + cols_to_move + cols[pos:]
    return df[new_cols]


# %% ../nbs/00_core.ipynb #8b6f1ad2
def clean_string(input_string:str):
    """Cleans input_string"""
    processed_string = "".join(c if c.isalnum() else "_" for c in input_string.lower()).strip("_")
    return "_".join(filter(None, processed_string.split("_")))

# %% ../nbs/00_core.ipynb #85b61e6b-1bc8-4568-a48d-4ab67db94a07
def clean_col_names(df):
    """Returns df with clean column names, supports both pandas and polars."""
    if isinstance(df, pd.DataFrame):
        df.columns = [clean_string(col) for col in df.columns]
        return df
    return df.rename({col: clean_string(col) for col in df.columns})

# %% ../nbs/00_core.ipynb #fb377cfc
def show_identical_columns(
    df: pd.DataFrame,  # The DataFrame to analyze
    columns: list      # The list of column names to compare
) -> pd.DataFrame:     # A DataFrame matrix showing identity status between columns
    "Checks if specified columns in `df` are identical."
    if not set(columns).issubset(df.columns):
        raise ValueError("One or more specified columns do not exist in the DataFrame.")

    column_matrix = pd.DataFrame(index=columns, columns=columns)
    for col_1, col_2 in itertools.combinations(columns, 2):
        column_matrix.loc[col_1, col_2] = all(df[col_1].eq(df[col_2]))

    return column_matrix

# %% ../nbs/00_core.ipynb #df4904fd
def reduce_mem_usage(
    df: pd.DataFrame | pd.Series, # Input DataFrame or Series
    verbose: bool = True          # Whether to print memory usage reduction
    ) -> pd.DataFrame | pd.Series:    # Reduced DataFrame or Series
    """Reduces memory usage of a DataFrame or Series by downcasting numerical types."""
    numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

    if isinstance(df, pd.DataFrame):
        start_mem = df.memory_usage().sum() / 1024**2
    else:  # it's a Series
        start_mem = df.memory_usage() / 1024**2

    for col in df.columns if isinstance(df, pd.DataFrame) else [df.name]:
        col_type = df[col].dtypes if isinstance(df, pd.DataFrame) else df.dtypes
        if col_type in numerics:
            c_min = df[col].min() if isinstance(df, pd.DataFrame) else df.min()
            c_max = df[col].max() if isinstance(df, pd.DataFrame) else df.max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8) if isinstance(df, pd.DataFrame) else df.astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16) if isinstance(df, pd.DataFrame) else df.astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32) if isinstance(df, pd.DataFrame) else df.astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64) if isinstance(df, pd.DataFrame) else df.astype(np.int64)
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16) if isinstance(df, pd.DataFrame) else df.astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32) if isinstance(df, pd.DataFrame) else df.astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64) if isinstance(df, pd.DataFrame) else df.astype(np.float64)

    if isinstance(df, pd.DataFrame):
        end_mem = df.memory_usage().sum() / 1024**2
    else:  # it's a Series
        end_mem = df.memory_usage() / 1024**2

    if verbose:
        print('Mem. usage decreased to {:5.2f} Mb ({:.1f}% reduction)'.format(end_mem, 100 * (start_mem - end_mem) / start_mem))

    return df

# %% ../nbs/00_core.ipynb #9ae5abea
def group_resample(
    df: pd.DataFrame,      # Input DataFrame
    id_col: str,           # Column name to group/unstack by
    value_col: str,        # Column name containing values to aggregate
    date_col: str,         # Column name containing dates
    freq: str = "W",       # Resampling frequency (e.g., 'W', 'ME', 'D')
    aggfunc: str = "sum"   # Aggregation function (e.g., 'sum', 'mean')
    ) -> pd.DataFrame:         # Resampled and stacked DataFrame
    "Group, resample, and restack a DataFrame by ID and date."
    return (
        df.groupby([date_col, id_col])
        .agg({value_col: aggfunc})
        .unstack(id_col)
        .resample(freq)
        .sum()
        .stack(id_col)
        .reset_index()
    )

# %% ../nbs/00_core.ipynb #3fba095f
def polars_resample(df, date_col='ds', group_cols='unique_id', agg_col='y', frequency='1mo'):
    if isinstance(group_cols, str):
        group_cols = [group_cols]

    df = df.with_columns(pl.col(date_col).dt.truncate(frequency))
    agg_df = df.group_by([date_col] + group_cols).agg(pl.col(agg_col).sum())

    dates = pl.date_range(
        agg_df[date_col].min(), agg_df[date_col].max(),
        interval=frequency, eager=True
    ).alias(date_col)

    groups = agg_df.select(group_cols).unique()
    grid = pl.DataFrame({date_col: dates}).join(groups, how='cross')

    return grid.join(agg_df, on=[date_col] + group_cols, how='left').with_columns(pl.col(agg_col).fill_null(0)).sort([*group_cols, date_col])
